# -*- coding: utf-8 -*-
"""Copy of Copy of Assignment1(Ramachalpandey).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oxOL6qnbBdP_7QR4JNCpDnPfYk9XoGIT
"""

x = [int (i) for i in input("Enter the values:").split()]
print(x)
print(sum(x))